version: '3.3'

services:
  flowers-web-application:
    #image: in28min/todo-web-application-mysql:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    restart: always
    depends_on: # Start the depends_on first
      - mysql 
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3307
      RDS_DB_NAME: 1800f
      RDS_USERNAME: root
      RDS_PASSWORD: root
    networks:
      - 1800f-network

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3307"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: 1800f
    volumes:
      - mysql-database-data-volume:/var/lib/mysql
    networks:
      - 1800f-network  
  
# Volumes
volumes:
  mysql-database-data-volume:

networks:
  1800f-network: